import { UserProfile } from '@/types';

export const DEMO_USERS: Record<string, UserProfile & { collegeName?: string }> = {
  'admin@secureexam.demo': {
    id: 'demo-super-admin-01',
    full_name: 'Harsh Wagh',
    email: 'admin@secureexam.demo',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    college_id: null,
    collegeName: 'Central Examination Authority',
    last_login_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'exam.admin@secureexam.demo': {
    id: 'demo-exam-admin-01',
    full_name: 'Prof. Rajesh Kumar',
    email: 'exam.admin@secureexam.demo',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    role: 'EXAM_ADMIN',
    status: 'ACTIVE',
    college_id: null,
    collegeName: 'University Exam Controller Board',
    last_login_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'setter@secureexam.demo': {
    id: 'demo-setter-01',
    full_name: 'Dr. Ananya Sharma',
    email: 'setter@secureexam.demo',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
    role: 'QUESTION_SETTER',
    status: 'ACTIVE',
    college_id: null,
    collegeName: 'Department of Computer Science',
    last_login_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'college@secureexam.demo': {
    id: 'demo-college-admin-01',
    full_name: 'Principal V. S. Patil',
    email: 'college@secureexam.demo',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    role: 'COLLEGE_ADMIN',
    status: 'ACTIVE',
    college_id: 'c1000000-0000-0000-0000-000000000001',
    collegeName: 'Pune Institute of Computer Technology (PICT)',
    last_login_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'invigilator@secureexam.demo': {
    id: 'demo-invigilator-01',
    full_name: 'Prof. Suresh Mehta',
    email: 'invigilator@secureexam.demo',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=256',
    role: 'INVIGILATOR',
    status: 'ACTIVE',
    college_id: 'c1000000-0000-0000-0000-000000000001',
    collegeName: 'PICT Exam Center 04',
    last_login_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'auditor@secureexam.demo': {
    id: 'demo-auditor-01',
    full_name: 'Vikramaditya Rao',
    email: 'auditor@secureexam.demo',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=256',
    role: 'AUDITOR',
    status: 'ACTIVE',
    college_id: null,
    collegeName: 'Independent Security Audit Directorate',
    last_login_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'pending@secureexam.demo': {
    id: 'demo-pending-01',
    full_name: 'New Faculty Member',
    email: 'pending@secureexam.demo',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=256',
    role: 'PENDING',
    status: 'PENDING',
    college_id: null,
    last_login_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
};
